### ISSUE TITLE
What to do with existing .jpg files in a directory

### ISSUE THREAD

**Issue by TomasBeuzen** [UNCG-DAISY/PyWebCAT#14]
If you run webcat_utils more than once for the same station+datetime but with a different "save frame interval", the existing .csv metadata will be overwritten, but the existing .jpg frames will not be. We have two options:

1. Clear any existing .jpg files in a directory that already exists
2. Append new metadata to the existing .csv rather than overwriting it (and keep existing .jpg files).

**Comment by ebgoldstein** [comment]
my vote is for option 1: 
>Clear any existing .jpg files in a directory that already exists

we can write in the readme or example notebook that this is the behavior. I can't see a use case where appending metadata is better (its not that heavy of a computational burden to repull data if a user makes a mistake)
