### ISSUE TITLE
Improve the testing framework and code coverage

### ISSUE THREAD

**Issue by TomasBeuzen** [UNCG-DAISY/PyWebCAT#15]
This is also somewhat related to #12 but testing of functionality with pytest and code coverage need to be improved. I might also implement some GitHub actions for automating this, as well as black formatting.

**Comment by TomasBeuzen** [comment]
To integrate some GHA into this repo, I'll need access to the repo settings to add secret keys (or get someone else to do it). If this is something we want to do (e.g., for auto code coverage, formatting, testing, etc) we can discuss.

**Comment by ebgoldstein** [comment]
you should have admin privelages now..

**Comment by TomasBeuzen** [comment]
Confirmed thanks! Will integrate some CI next week!

**Comment by TomasBeuzen** [comment]
All done! Integrated a little bit of [CI with GitHub actions](https://github.com/UNCG-DAISY/PyWebCAT/blob/master/.github/workflows/build.yml) for code formatting and testing. Test reports are uploaded to codecov. CI is triggered on push/pull request to master branch.

Edit: coverage is it at 87% because I don't want to run the url downloading functions every time. These tests have been written in [test_pywebcat.py](https://github.com/UNCG-DAISY/PyWebCAT/blob/fd19b47b136e60a3dd38552da9afbcc38cfe448c/tests/test_pywebcat.py#L40) but are commented out.
