### ISSUE TITLE
release

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/PyWebCAT#18]
I enabled the Zenodo webhook, so when we decide on https://github.com/UNCG-DAISY/PyWebCAT/issues/17 and https://github.com/UNCG-DAISY/PyWebCAT/issues/9 we should:

- [x] make a release (job for @TomasBeuzen )
- [x] tidy up the citation formatting as Beuzen and Goldstein, etc. (job for @ebgoldstein  )

**Comment by TomasBeuzen** [comment]
Release tagged!
