### ISSUE TITLE
grab frames from metadata

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/PyWebCAT#9]
data releases will have the tags + the csv'ed metadata (from `wc.save_frames`).

we might want to have a way to grab frames directly from metadata record (i.e., for rehydrating the tagged data release)

**Comment by TomasBeuzen** [comment]
The .csv metadata structure is updated in #11. Seeing the revised structure might help in thinking about how to do this "rehydrating")

**Comment by ebgoldstein** [comment]
I will write an example/snippet of code that we provide in `/notebooks` for how to do this.

**Comment by ebgoldstein** [comment]
actually, I think this is out of scope RN — i'll put it in the repository for the ML work when we get there and have the labeled data
